config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"

  resources :users, except: [:create, :show]
  post :create_user, to: 'users#create'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:create], defaults: { format: 'json'} do
        post :deactivate
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]

  def self.ransackable_attributes(auth_object = nil)
    ["active", "email", "name", "role"]
  end

  def ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s }
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def create
        user = User.new(user_params)

        if user.save!
          render json: 'Created Successfully!', status: 201
        else
          errors = []
          user.errors.each { |error| errors << error.full_message }
          render json: { errors: errors }, status: 422
        end
      end

      def deactivate
        user = User.find(params[:user_id])

        if user.active?
          user.toggle!(:active)
          render json: 'User successfully deactivated!', status: 200
        else
          render json: { error: 'User already deactivated!' }, status: 422
        end
      end

      private
      def user_params
        params.require(:user).permit!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  include Pundit::Authorization

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:index, :new, :create]
  before_action :set_roles_options, only: [:edit, :new, :create]

  # caches_action :index, expires_in: 10.minutes

  def index
    @q = User.ransack(params[:q])
    @users = @q.result
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Created successfully!' }
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end


  def edit
    authorize @user
  end

  def update
    authorize @user

    if @user.update!(user_params)
      redirect_to root_path, notice: 'Updated successfully!'
    else
      render :edit
    end
  end

  def destroy
    authorize @user

    @user.destroy!

    redirect_to root_path, notice: 'Deleted successfully!'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_roles_options
    @roles = User.roles.keys.to_a
  end

  def user_params
    params.require(:user).permit(:name, :active, :role, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portabilis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-blue-100">
    <main class="container mx-auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="w-full mx-auto max-w-lg h-auto bg-white shadow-md rounded px-8 pt-11 pb-8 mt-11 mb-11">
  <h1 class="text-gray-900 text-2xl text-center mb-5 font-medium title-font">Edit User</h1>
  <%= form_with model: @user do |f| %>
    <div class="relative mb-4 field">
      <%= f.label :name, class: "leading-7 text-sm text-gray-600" %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
    </div>
    <div class="relative mb-4 field">
      <div class="grid grid-cols-2">
        <div>
          <%= f.label :active, class: "leading-7 text-sm text-gray-600" %><br>
          <%= f.check_box :active %>
        </div>
        <div>
          <%= f.label :role, class: "leading-7 text-sm text-gray-600" %><br>
          <%= f.select :role, @roles %>
        </div>
      </div>
    </div>
    <div class="relative mt-10 actions text-center">
      <%= f.submit "Update User", class: "text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg" %>
      <%= link_to 'Back', root_path, class: "text-md font-medium text-blue-600 hover:underline align-right" %>
    </div>
  <% end %>
</div>

app/views/users/_search.html.erb
<%= search_form_for @q do |f| %>
  <div class="grid grid-cols-5 gap-2 items-center">
    <div class="p-3 ml-11">
      <%= f.label :name %><br>
      <%= f.search_field :name_cont %>
    </div>
    <div class="p-3 ml-11">
      <%= f.label :email %><br>
      <%= f.search_field :email_cont %>
    </div>
    <div class="p-3 ml-11 col-span-3 grid grid-cols-3 gap-2">
      <div>
        <%= f.label :active %><br>
        <%= f.select :active_eq, [['Active', true], ['Inactive', false]], include_blank: 'All' %>
      </div>
      <div class="mr-11">
        <%= f.label :role %><br>
        <%= f.select :role_eq, [['User', 0], ['Admin', 1]], include_blank: 'All' %>
      </div>
      <div class="p-5 mr-11">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr class="bg-white border-b-1">
  <td class="px-6 py-4"><%= user.name %></td>
  <td class="px-6 py-4"><%= user.email %></td>
  <td class="px-6 py-4"><%= user.role %></td>
  <td class="px-6 py-4"><%= user.active %></td>
  <td class="px-6 py-4">
    <% if UserPolicy.new(current_user, user).edit? %>
      <%= link_to 'Edit', edit_user_path(user), id: "edit_user_#{user.id}", class: "focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-4 py-2 mr-2 mb-2" %>
    <% end %>
    <% if UserPolicy.new(current_user, user).destroy? %>
      <%= link_to 'Destroy', user, id: "delete_user_#{user.id}", data: { turbo_method: :delete }, class: "focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2 mb-2" %>
    <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<h2>Edit user</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container mx-auto">
  <div class="mx-auto relative overflow-x-auto w-full max-w-7xl h-full bg-white border border-gray-200 rounded-lg shadow mt-11">
    <% if user_signed_in? %>
      <p class="mx-auto text-right m-5 pr-10">
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-md font-medium text-blue-600 hover:underline align-right" %>
      </p>
    <% end %>

    <p class="text-center text-slate-700 text-4xl mt-5 mb-11">Users</p>

    <div class="mx-auto">
      <%= render 'search' %>
    </div>

    <% if UserPolicy.new(current_user, User.new).new? %>
      <p class="mx-auto w-1/2 text-right mb-3 mt-11">
        <%= link_to 'New User', new_user_path, id: 'new_user', class: "text-md font-medium text-blue-600 hover:underline align-right" %>
      </p>
    <% end %>
    <table class="text-sm text-left text-gray-500 mx-auto rounded-lg p-10 shadow-lg mb-11">
      <thead class="text-xs text-gray-700 uppercase bg-gray-100">
        <tr>
          <th scope="col" class="px-6 py-3"><%= sort_link(@q, :name, 'Name') %></th>
          <th scope="col" class="px-6 py-3"><%= sort_link(@q, :email, 'Email') %></th>
          <th scope="col" class="px-6 py-3"><%= sort_link(@q, :role, 'Role') %></th>
          <th scope="col" class="px-6 py-3"><%= sort_link(@q, :active, 'Status') %></th>
          <th scope="col" class="px-6 py-3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="w-full mx-auto max-w-lg h-auto bg-white shadow-md rounded px-8 pt-11 pb-8 mt-11 mb-11">
  <h1 class="text-gray-900 text-2xl text-center mb-5 font-medium title-font">New User</h1>
  <%= form_for User.new, url: create_user_path, method: :post do |f| %>
    <div class="relative mb-4 field">
      <%= f.label :name, class: "leading-7 text-sm text-gray-600" %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
    </div>
    <div class="relative mb-4 field">
      <%= f.label :email, class: "leading-7 text-sm text-gray-600" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
    </div>
    <div class="relative mb-4 field">
      <%= f.label :password, class: "leading-7 text-sm text-gray-600" %><br />
      <%= f.password_field :password, autofocus: true, autocomplete: "new-password", class: "w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
    </div>
    <div class="relative mb-4 field">
      <div class="grid grid-cols-2">
        <div>
          <%= f.label :active, class: "leading-7 text-sm text-gray-600" %><br>
          <%= f.check_box :active %>
        </div>
        <div>
          <%= f.label :role, class: "leading-7 text-sm text-gray-600" %><br>
          <%= f.select :role, @roles %>
        </div>
      </div>
    </div>
    <div class="relative mt-10 actions text-center">
      <%= f.submit "Create User", class: "text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg" %>
      <%= link_to 'Back', root_path, class: "text-md font-medium text-blue-600 hover:underline align-right" %>
    </div>
  <% end %>
</div>